### ISSUE TITLE
support of Philips Hue lights is very important !!!!!!!

### ISSUE THREAD

**Issue by digiTaler1** [Speedy1985/enigmalight#4]

**Comment by bigfreak85** [comment]
For Example see: http://blog.krannich.de/2014/11/ambilight-mit-boblight-und-philips-hue-bridge/

**Comment by Newan** [comment]
Cannot start python output:
[device]
name hue
output python /usr/dreamWifiLight/dkhue.py
channels 6
type popen
interval 200000
debug off

log:
EnigmaLight (c) 2014 Speedy1985 and Oktay Oeztueter.
(Based on Boblight (c) 2009 by Bob Loosen)

[InitLog]                       start of log /home/elight-addons/.enigmalight/enigmalight.log
[CConfig::LoadConfigFromFile]   Opening /etc/enigmalight.conf
[CConfig::CheckConfig]          checking config lines
[CConfig::CheckConfig]          config lines valid
[CConfig::LoadConfigFromFile]   Opening /etc/enigmalight.conf
[CConfig::BuildConfig]          building config
[CConfig::BuildConfig]          built config successfully
[main]                          Start device 1 from 2
[main]                          Start device 2 from 2
"CDevice::Process]              hue: starting with output "python /usr/dreamWifiLight/dkhue.py
[CDevice::Process]              hue: setting up
[CDevice::Process]              ambilight: starting with output "/dev/ttyUSB0"
[CDevice::Process]              ambilight: setting up
[CDevice::Process]              hue: setup succeeded
[CDevice::Process]              ambilight: setup succeeded
[CEnigmaLight::SetColorSequence]Set colorsequence to RGB
set adjust 0 0 0
 1[CFlagManager::SetVideoGamma]   Gamma not set, using 2.2 since this is default for video
[CMainLoop::Process]            Starting grabber..
[CGrabber::Setup]               Lights: 107, Cluster leds: 1 as one led
[CGrabber::Setup]               Channels: 321
[CGuiServer::Process]           Start GuiServer
[CGuiServer::Process]           Opening listening socket for Enigma2 GUI on 127.0.0.1:6767
[CGrabber::Setup]               Interval: 0.10
[CGrabber::Run]                 Mode -> Dynamic
[CStb::DetectSTB]               Detect STB-Type...
[CStb::DetectSTB]               Detected STB-Type: BCM7405
[CFrameGrabber::Setup]          Open memory /dev/mem
[CFrameGrabber::CheckRes]       Set Scanrange to 90x67 (Source 1440x1080)
[CGuiServer::Process]           GuiClient 127.0.0.1:47753 connected successful.
': [Errno 2] No such file or directoryiLight/dkhue.py
root@dm800se:~# python /usr/dreamWifiLight/dkhue.py
^CTraceback (most recent call last):
  File "/usr/dreamWifiLight/dkhue.py", line 159, in <module>
    popen()
  File "/usr/dreamWifiLight/dkhue.py", line 17, in popen
    eingabe = sys.stdin.readline()
